FROM centos:centos7

MAINTAINER Rômulo Jales <romulo@romulojales.com>

run yum install http://dl.fedoraproject.org/pub/epel/beta/7/x86_64/epel-release-7-0.2.noarch.rpm -y
run yum install supervisor -y
add supervisord.conf /etc/supervisord.conf
run yum clean all -y


