from romulojales/nginx

#intalling uwsgi
run rm -rf /etc/nginx/conf.d/*
add default-uwsgi.conf /etc/nginx/conf.d/

run yum upgrade -y
run yum install gcc python-devel python-setuptools -y
run easy_install pip
run pip install uwsgi

